apiVersion: apps/v1
kind: Deployment
metadata:
  name: p8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p8
  template:
    metadata:
      labels:
        app: p8
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p8
        ports:
        - containerPort: 80
